bk_example_v2 2/urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""


from django.conf.urls import include, url
from django.contrib import admin

"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

urlpatterns = [
    # Django后台数据库管理
    url(r"^admin/", admin.site.urls),
    # 用户登录鉴权--请勿修改
    url(r"^account/", include("blueapps.account.urls")),
    # 在home_application(根应用)里开发你的应用的主要功能
    url(r"^", include("home_application.urls")),
    # 如果你习惯使用 mako 模板，可在mako_application开发你的应用的主要功能
    url(r"^mako/", include("mako_application.urls")),
    # 样例功能
    url(r"^example/", include("blueapps_example.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
]


# 添加版本日志功能
try:
    import version_log.config as config
    
    urlpatterns += [
        url(r'^{}'.format(config.ENTRANCE_URL), include('version_log.urls')),
    ]
except ImportError:
    pass

bk_example_v2 2/version_log/urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.conf.urls import url

from version_log import views

app_name = "version_log"

urlpatterns = (
    # 版本日志单页面
    url(r'^$', views.version_logs_page, name='version_log_page'),
    # 获取版本日志块页面（用于对话框场景）
    url(r'^block/$', views.version_logs_block, name='block'),
    # 获取版本日志列表
    url(r'^version_logs_list/$', views.version_logs_list, name='version_logs_list'),
    # 获取版本日志详情
    url(r'^version_log_detail/', views.get_version_log_detail, name='version_log_detail'),
)

bk_example_v2 2/version_log/models.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

from django.db import models
from django.utils.translation import ugettext_lazy as _

from version_log.utils import is_later_version
from version_log.config import NO_VERSION_CONSTANT


class VersionLogVisitedManager(models.Manager):
    def has_visit_latest(self, username, latest_version):
        """判断用户是否访问过最新版本日志，同时更新数据库记录"""
        if not self.filter(username=username).exists():
            return False
        user_version = self.get(username=username).visited_version
        user_version = None if user_version == NO_VERSION_CONSTANT else user_version
        if is_later_version(latest_version, user_version):
            return False
        if is_later_version(user_version, latest_version):
            self.update_visit_version(username, latest_version)
        return True

    def update_visit_version(self, username, visit_version):
        """更新用户访问版本记录"""
        if visit_version is None:
            visit_version = NO_VERSION_CONSTANT
        self.update_or_create(username=username, defaults={'visited_version': visit_version})


class VersionLogVisited(models.Model):
    username = models.CharField(primary_key=True, max_length=50, verbose_name=_(u'用户名'))
    visited_version = models.CharField(max_length=20, verbose_name=_(u'访问版本'))

    objects = VersionLogVisitedManager()

    class Meta:
        verbose_name = verbose_name_plural = _(u'版本日志访问记录')

bk_example_v2 2/version_log/views.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""

import logging

from django.shortcuts import render
from django.http import JsonResponse
from django.utils.translation import ugettext_lazy as _

from version_log import config
from version_log.utils import get_version_list, get_parsed_html

logger = logging.getLogger(__name__)


def version_logs_page(request):
    """版本日志页面"""
    version_list = get_version_list()
    if version_list is None:
        logger.error('MD_FILES_DIR not found. Current path is {}'.format(config.MD_FILES_DIR))
        version_list = []  # 用无日志文件提示对用户屏蔽错误
    else:
        version_list = [{'version': version, 'date': date} for (version, date) in version_list]
    context = {
        'version_list': version_list,
        'page_title': config.PAGE_HEAD_TITLE,
        'ENTRANCE_URL': config.ENTRANCE_URL,
        'USE_HASH_URL': config.USE_HASH_URL
    }
    if config.PAGE_STYLE == 'dialog':
        return render(request, 'version_log/version_logs_dialog_page.html', context)
    else:
        return render(request, 'version_log/version_logs_page.html', context)


def version_logs_block(request):
    """版本日志数据块"""
    return render(request, 'version_log/version_logs_block.html')


def version_logs_list(request):
    """获取版本日志列表"""
    version_list = get_version_list()
    if version_list is None:
        logger.error('MD_FILES_DIR not found. Current path is {}'.format(config.MD_FILES_DIR))
        return JsonResponse({'result': False, 'code': -1, 'message': _(u'访问出错，请联系管理员。'), 'data': None})
    response = {'result': True, 'code': 0, 'message': _(u'日志列表获取成功'), 'data': version_list}
    return JsonResponse(response)


def get_version_log_detail(request):
    """获取单条版本日志转换结果"""
    log_version = request.GET.get('log_version')
    html_text = get_parsed_html(log_version)
    if html_text is None:
        logger.error('md file not found or log version not valid. Log version is {}'.format(log_version))
        response = {'result': False, 'code': -1, 'message': _(u'日志版本文件没找到，请联系管理员'), 'data': None}
        return JsonResponse(response)
    response = {'result': True, 'code': 0, 'message': _(u'日志详情获取成功'), 'data': html_text}
    return JsonResponse(response)

bk_example_v2 2/version_log/templates/version_log/version_logs_block.html
{% load static %}
<link rel="stylesheet" href="{% static 'version_log/css/version-log-page.css' %}">
<link rel="stylesheet" href="{% static 'version_log/css/jquery.mCustomScrollbar.css' %}">
<script src="{% static 'version_log/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<div>
    <div class="vlog">
        <div class="vlog-nav">
            <div class='vlog-nav-btn' id="btn_up" onclick="log_list_move(false)" style="top: 0;border-bottom: 1px solid #ddd;">
                <img class="logo-direction" src="{% static 'version_log/images/up.svg' %}" style="width:20px;height:13px;opacity:0.4;" />
            </div>
            <div class="vlog-list">
                <ul class="nav vlog-nav-ul" id="version_log_list">
                    <!-- version logs list  -->
                </ul>
                <div id="vlog-line" style="border-right: 1px solid #ddd; float: right;"></div>
            </div>
            <div class='vlog-nav-btn' id="btn_down" onclick="log_list_move(true)" style="bottom: 0;border-top: 1px solid #ddd;">
                <img class="logo-direction" src="{% static 'version_log/images/down.svg' %}" style="width:20px;height:13px;opacity:0.4;" />
            </div>
        </div>
        <div id="vlog-detail" class="vlog-content tab-content">
            <div class="tab-pane active" id="log_pane">
                <div id="version_log_detail">
                    <!-- detail version log -->
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let is_btn_show = false;
    $(function() {
        // load version logs list
        $.ajax({
            url: "{% url 'version_log:version_logs_list' %}",
            type: "GET",
            dataType: "json",
            success: function(data) {
                if (data.code == 0) {
                    data = data.data;
                    var nav_ul = $('#version_log_list');
                    data.forEach(function(item, i) {
                        nav_ul.append('<li data-toggle="pill"><a href="#" onclick="log_detail(this);"> <span>' + item[0]
                        + '</span><br><span style="font-size:12px;">'+ item[1] +'</span></a></li>');
                    });
                    // load the lastest version log
                    if (data.length > 0) {
                        nav_ul.find('a').get(0).click();
                        const line_height = 600-65*data.length+'px';
                        $("#vlog-line").css({'height': line_height});
                    } else {
                        show_error_page(gettext('暂无版本日志'));
                    }
                } else {
                    show_error_page(gettext('页面异常，请稍后重试'));
                }
            }
        });
        $("#log_pane").mCustomScrollbar({
            setHeight:600,
            theme:"minimal-dark"
        });

        // control buttons when the mouse move into the list
        $(".vlog-nav").hover(
            function () {
                is_btn_show = true;
                show_nav_btn();
            },
            function () {
                is_btn_show = false;
                show_nav_btn();
            }
        );

        // control buttons when scroll the list
        $(".vlog-list").scroll(function(event){
            show_nav_btn();
        });
    });

    // determine the buttons show or hide
    function show_nav_btn() {
        const top = $(".vlog-list").scrollTop();
        const window_height = $(".vlog-list").height();
        const list_height = $("#version_log_list").height();
        if (top > 0 && is_btn_show) {
            $("#btn_up").show();
        } else {
            $("#btn_up").hide();
        }
        if (top+window_height < list_height && is_btn_show) {
            $("#btn_down").show();
        } else {
            $("#btn_down").hide();
        }
    }

    // load detail version log
    function log_detail(element) {
        var log_version = $(element).find("span").first().text();
        $.ajax({
            url: "{% url 'version_log:version_log_detail' %}" + "?log_version=" + log_version,
            type: "GET",
            dataType: "json",
            success: function(data) {
                if (data.code == 0) {
                    data = data.data;
                    $("#version_log_detail").html(data);
                } else {
                    show_error_page(gettext('页面异常，请稍后重试'));
                }

            }
        });
    }

    // button event to scroll the log list
    function log_list_move(isNext) {
        if (isNext === true) {
            $(".vlog-list").animate({
                'scrollTop' : "+=300px"
            }, 500);
        } else {
            $(".vlog-list").animate({
                'scrollTop' : "-=300px"
            }, 500);
        }
    }

    function show_error_page(text) {
        html_tpl = `
        <div class="bk-exception" style="text-align: center;height:100%;padding:10%">
            <img src="{% static 'version_log/images/error.png' %}" >
            <h2 class="exception-text">` + text + `</h2>
        </div>
        `;
        $(".vlog").html(html_tpl);
    }
</script>

bk_example_v2 2/version_log/templates/version_log/version_logs_dialog_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
    <link rel="stylesheet" href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://magicbox.bk.tencent.com/static_api/v3/assets/artDialog-6.0.4/css/ui-dialog.css">
    <script type="text/javascript" src="{% url 'version_log:javascript-catalog' %}"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/artDialog-6.0.4/dist/dialog-min.js"></script>
    <script>
        function show_modal() {
            load_modal_frame("{% url 'version_log:block' %}");
        }

        function load_modal_frame(url) {
            $.ajax({
                url: url,
                type: "GET",
                dataType: "html",
                success: function(data) {
                    var d = dialog({
                        height: 600,
                        width: 1105,
                        title: gettext('版本日志'),
                        content: data,
                    });
                    d.showModal();
                }
            })
        }

        // 获取指定的Cookie
        function getCookie(name) {
            var value = "; " + document.cookie;
            var parts = value.split("; " + name + "=");
            if (parts.length === 2) return parts.pop().split(";").shift();
        }

        // 如果存在Cookie SHOW_VERSION_LOG值为True，则弹出版本日志弹窗
        if (getCookie("SHOW_VERSION_LOG") === "True") {
            $(document).ready(function () {
                show_modal()
                // 清除Cookie避免重复弹窗
                document.cookie = "SHOW_VERSION_LOG=; path=/; expire=Thu, 01 Jan 1970 00:00:01 GMT;"
            })
        }
    </script>
</head>
<body>
</body>
    <script type="text/javascript">
        $(function () {
            show_modal();
            // waiting for modal loading
            setTimeout(() => {
                $('.ui-dialog-close').click(function () {
                    history.back(-1)
                });
            }, 500);
        });
    </script>
</html>

bk_example_v2 2/version_log/templates/version_log/version_logs_page.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
    <link rel="stylesheet" href="{% static 'version_log/css/version-log-gitbook-page.css' %}">
    <link rel="stylesheet" href="{% static 'version_log/css/jquery.mCustomScrollbar.css' %}">
    <link rel="stylesheet" href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css">
</head>
<body>
    <div class="logs-list">
        <ul>
            {% for version in version_list %}
                <li data-toggle="pill" onclick="log_detail('{{version.version}}')"> 
                    <span>{{ version.version }}<span>
                    <br>
                    <span style="font-size: 14px;">{{ version.date }}<span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="log-body">
        <div class="page-head" style="margin-top: 5px; padding: 5px 10px;">
            <img onclick="back()" src="{% static 'version_log/images/back.svg' %}" title="{% trans '返回' %}" style="width:18px;height:18px; cursor:pointer; margin-left:10px;" />
        </div>
        <div class="page-inner">
            <div id="log-detail">
                <!-- detail version log -->
            </div>
        </div>
    </div>
    
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
<script src="{% static 'version_log/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script>
    $(function() {
        var versions = {{ version_list | safe }};
        if (versions.length > 0) {
            // if exist version log, request the latest one.
            log_detail(versions[0].version);
            $('.logs-list li:first-child').addClass('active');
        } else {
            show_error_page(gettext('暂无版本日志'));
        }

        $(".logs-list").mCustomScrollbar({
            setHeight:'100%',
            theme:"minimal-dark"
        });
        $(".log-body").mCustomScrollbar({
            setHeight:'100%',
            theme:"minimal-dark"
        });
    })

    // load detail version log
    function log_detail(log_version) {
        $.ajax({
            url: "{% url 'version_log:version_log_detail' %}" + "?log_version=" + log_version,
            type: "GET",
            dataType: "json",
            success: function(data) {
                if (data.code == 0) {
                    data = data.data;
                    $("#log-detail").html(data);
                } else {
                    show_error_page(gettext('页面异常，请稍后重试'));
                }

            }
        })
    }

    function back() {
        history.back(-1);
    }

    function show_error_page(text) {
        html_tpl = `
        <div class="bk-exception" style="text-align: center;height:100%;padding:10%">
            <img src="{% static 'version_log/images/error.png' %}" >
            <h2 class="exception-text">` + text + `</h2>
        </div>
        `;
        $("#log-detail").html(html_tpl);
    }

</script>
</body>
</html>